### ISSUE TITLE
Invalid callback/fallback url gives misleading error message

### ISSUE THREAD

**Issue by zaporylie** [vippsas/vipps-ecom-api#53]
When the fallback/callback url is considered invalid - local or does't validate with UrlValidator - misleading error message is dispatched, giving bad DX (Developer Experience):

`merchantInfo.fallBack.invalid: Fallback should not be null or empty`

for fallback url: `http://localhost/fallback`

The error message should reflect that fallback url is invalid, rather than null or empty.

**Comment by cloveras** [comment]
Hi, and thanks for reporting this! 

We are looking into it, sorry for not updating here earlier. The error message could be better. I actually looked into this one myself a while ago, but that ended up in "just" using a better validator, and the error message was left unchanged (not trivial to fix, strangely). 

Christian, Vipps

**Comment by cloveras** [comment]
Hello again

This was fixed a while ago, sorry for the lack of follow-up here.

Christian, Vipps

**Comment by zaporylie** [comment]
@cloveras Seems like this issue is still affecting developers, even though you said it has been fixed. See https://www.drupal.org/project/commerce_vipps/issues/3098969 for details.

**Comment by augustks** [comment]
@cloveras Still an issue.

When sending an intiate payment request with a valid CallbackPrefix, the eCom API returns a misleading error message.
The CallbackPrefix had an additional slash after the domain name (valid afaik), but not null or empty.

Error response:
```json
[{
	"errorGroup": "Merchant",
	"errorCode": "merchantInfo.callbackPrefix.invalid",
	"errorMessage": "CallbackPrefix should not be null or empty",
	"contextId": "<some guid>"
}]
```

Example request:
```json
{
  "customerInfo": {
  },
  "merchantInfo": {
    "merchantSerialNumber": "123456",
    "callbackPrefix":"https://example.com//vipps/callbacks-for-payment-update",
    "fallBack": "https://example.com//vipps/fallback-result-page/order123abc"
  },
  "transaction": {
    "orderId": "order123abc",
    "amount": 20000,
    "transactionText": "One pair of Vipps socks"
  }
}
```
